services:
  api-gateway-1:
    build:
      context: .
      dockerfile: apps/api-gateway/Dockerfile.dev
    volumes:
      - ./.env:/app/apps/api-gateway/.env
      - .:/app
      - /app/node_modules
  api-gateway-2:
    build:
      context: .
      dockerfile: apps/api-gateway/Dockerfile.dev
    volumes:
      - ./.env:/app/apps/api-gateway/.env
      - .:/app
      - /app/node_modules
  auth:
    build:
      context: .
      dockerfile: apps/auth/Dockerfile.dev
    volumes:
      - ./.env:/app/apps/auth/.env
      - .:/app
      - /app/node_modules
  products:
    build:
      context: .
      dockerfile: apps/products/Dockerfile.dev
    volumes:
      - ./.env:/app/apps/products/.env
      - .:/app
      - /app/node_modules
  cart-items:
    build:
      context: .
      dockerfile: apps/cart-items/Dockerfile.dev
    volumes:
      - ./.env:/app/apps/cart-items/.env
      - .:/app
      - /app/node_modules
  checkout:
    build:
      context: .
      dockerfile: apps/checkout/Dockerfile.dev
    volumes:
      - ./.env:/app/apps/checkout/.env
      - .:/app
      - /app/node_modules
  events-handler:
    build:
      context: .
      dockerfile: apps/events-handler/Dockerfile.dev
    volumes:
      - ./.env:/app/apps/events-handler/.env
      - .:/app
      - /app/node_modules
  orders:
    build:
      context: .
      dockerfile: apps/orders/Dockerfile.dev
    volumes:
      - ./.env:/app/apps/orders/.env
      - .:/app
      - /app/node_modules
