services:
  # build-base-image:
  #   build:
  #     context: .
  #     dockerfile: apps/base-images/Dockerfile.build
  # prod-base-image:
  #   build:
  #     context: .
  #     dockerfile: apps/base-images/Dockerfile.prod
  # api-gateway:
  #   build:
  #     context: .
  #     dockerfile: apps/api-gateway/Dockerfile
  api-gateway-1:
    build:
      context: .
      dockerfile: apps/api-gateway/Dockerfile
  api-gateway-2:
    build:
      context: .
      dockerfile: apps/api-gateway/Dockerfile
  auth:
    build:
      context: .
      dockerfile: apps/auth/Dockerfile
  products:
    build:
      context: .
      dockerfile: apps/products/Dockerfile
  cart-items:
    build:
      context: .
      dockerfile: apps/cart-items/Dockerfile
  checkout:
    build:
      context: .
      dockerfile: apps/checkout/Dockerfile
  events-handler:
    build:
      context: .
      dockerfile: apps/events-handler/Dockerfile
  orders:
    build:
      context: .
      dockerfile: apps/orders/Dockerfile
