services:
  api-gateway-1:
    container_name: api-gateway-1
    image: ghcr.io/gideonadeti/reen-backend-api-gateway-1:latest
    volumes:
      - ./.env:/app/apps/api-gateway/.env
  api-gateway-2:
    container_name: api-gateway-2
    image: ghcr.io/gideonadeti/reen-backend-api-gateway-2:latest
    volumes:
      - ./.env:/app/apps/api-gateway/.env
  nginx:
    container_name: nginx
    image: ghcr.io/gideonadeti/reen-backend-nginx:latest
    ports:
      - '80:80'
      - '443:443'
    depends_on:
      - api-gateway-1
      - api-gateway-2
    volumes:
      - ./cert.crt:/etc/nginx/certs/cert.crt
      - ./key.key:/etc/nginx/certs/key.key
  auth:
    container_name: auth
    image: ghcr.io/gideonadeti/reen-backend-auth:latest
    volumes:
      - ./.env:/app/apps/auth/.env
  products:
    container_name: products
    image: ghcr.io/gideonadeti/reen-backend-products:latest
    volumes:
      - ./.env:/app/apps/products/.env
