services:
  api-gateway-1:
    container_name: api-gateway-1
    build:
      context: .
      dockerfile: apps/api-gateway/Dockerfile
  api-gateway-2:
    container_name: api-gateway-2
    build:
      context: .
      dockerfile: apps/api-gateway/Dockerfile
    depends_on:
      - api-gateway-1
  nginx:
    container_name: nginx
    build:
      context: .
      dockerfile: apps/nginx/Dockerfile
    ports:
      - '80:80'
      - '443:443'
    depends_on:
      - api-gateway-2
  auth:
    container_name: auth
    build:
      context: .
      dockerfile: apps/auth/Dockerfile
    depends_on:
      - nginx
  products:
    container_name: products
    build:
      context: .
      dockerfile: apps/products/Dockerfile
    depends_on:
      - auth
  cart-items:
    container_name: cart-items
    build:
      context: .
      dockerfile: apps/cart-items/Dockerfile
    depends_on:
      - products
  checkout:
    container_name: checkout
    build:
      context: .
      dockerfile: apps/checkout/Dockerfile
    depends_on:
      - cart-items
  events-handler:
    container_name: events-handler
    build:
      context: .
      dockerfile: apps/events-handler/Dockerfile
    depends_on:
      - checkout
  orders:
    container_name: orders
    build:
      context: .
      dockerfile: apps/orders/Dockerfile
    depends_on:
      - events-handler
