services:
  api-gateway-1:
    container_name: api-gateway-1
    build:
      context: .
      dockerfile: apps/api-gateway/Dockerfile
  api-gateway-2:
    container_name: api-gateway-2
    build:
      context: .
      dockerfile: apps/api-gateway/Dockerfile
  checkout:
    container_name: checkout
    build:
      context: .
      dockerfile: apps/checkout/Dockerfile
  events-handler:
    container_name: events-handler
    build:
      context: .
      dockerfile: apps/events-handler/Dockerfile
  nginx:
    container_name: nginx
    build:
      context: .
      dockerfile: apps/nginx/Dockerfile
    ports:
      - '80:80'
    depends_on:
      - api-gateway-1
      - api-gateway-2
