services:
  # build-base-image:
  #   container_name: build-base-image
  # prod-base-image:
  #   container_name: prod-base-image
  # api-gateway:
  #   container_name: api-gateway
  #   volumes:
  #     - ./.env:/app/apps/api-gateway/.env
  api-gateway-1:
    container_name: api-gateway-1
    volumes:
      - ./.env:/app/apps/api-gateway/.env
  api-gateway-2:
    container_name: api-gateway-2
    volumes:
      - ./.env:/app/apps/api-gateway/.env
  nginx:
    container_name: nginx
    image: ghcr.io/gideonadeti/reen-backend-nginx:latest
    ports:
      - '80:80'
      - '443:443'
    depends_on:
      - api-gateway-1
      - api-gateway-2
    volumes:
      - ./cert.crt:/etc/nginx/certs/cert.crt
      - ./key.key:/etc/nginx/certs/key.key
  auth:
    container_name: auth
    volumes:
      - ./.env:/app/apps/auth/.env
  products:
    container_name: products
    volumes:
      - ./.env:/app/apps/products/.env
  cart-items:
    container_name: cart-items
    volumes:
      - ./.env:/app/apps/cart-items/.env
  checkout:
    container_name: checkout
    volumes:
      - ./.env:/app/apps/checkout/.env
  events-handler:
    container_name: events-handler
    volumes:
      - ./.env:/app/apps/events-handler/.env
  orders:
    container_name: orders
    volumes:
      - ./.env:/app/apps/orders/.env
  redis:
    container_name: redis
    image: redis:8.0.2
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    command: ['redis-server', '--appendonly', 'yes']

volumes:
  redis_data:
