services:
  api-gateway:
    container_name: api-gateway
    build:
      context: .
      dockerfile: apps/api-gateway/Dockerfile
    ports:
      - '3000:3000'
  auth:
    container_name: auth
    build:
      context: .
      dockerfile: apps/auth/Dockerfile
  products:
    container_name: products
    build:
      context: .
      dockerfile: apps/products/Dockerfile
