FROM ghcr.io/gideonadeti/reen-backend-build-base-image:latest as build
WORKDIR /app
COPY . .
CMD ["sh", "-c", "npx prisma generate --schema=apps/events-handler/prisma/schema.prisma && npm run start:dev events-handler"]

