FROM ghcr.io/gideonadeti/reen-backend-build-base-image:latest as build
WORKDIR /app
COPY . .
COPY libs/protos/src/*.proto dist/libs/protos/
WORKDIR /app/apps/orders
RUN npx prisma generate
WORKDIR /app
EXPOSE 5000
CMD ["npm", "run", "start:dev", "orders"]
