FROM ghcr.io/gideonadeti/reen-backend-build-base-image:latest as build
WORKDIR /app
EXPOSE 5003
CMD ["sh", "-c", "npx prisma generate --schema=apps/orders/prisma/schema.prisma && npm run start:dev orders"]
