FROM ghcr.io/gideonadeti/reen-backend-build-base-image:latest as build
WORKDIR /app
COPY . .
EXPOSE 5002
CMD ["sh", "-c", "npx prisma generate --schema=apps/cart-items/prisma/schema.prisma && npm run start:dev cart-items"]

